name: example_nearby
description: Flutter nearby example project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_beacon: ^0.5.1
  flutter_ble_peripheral: ^1.1.1
  flutter_reactive_ble: ^5.0.3
  get: ^4.6.5
  permission_handler: ^10.2.0
  
  # flutter_nearby_connections: ^1.1.1
  # 20 months ago
  # 
  # bluetooth_identifiers: ^1.1.1
  # 51 days ago
  # 
  # flutter_blue_plus: ^1.4.0
  # 49 days ago
  # 
  # ble_reader: ^0.1.1
  # 3 months ago
  # 
  # fluetooth: ^0.0.6
  # 24 days ago
  # 
  # flutter_bluetooth_basic_v2: ^0.0.6
  # 3 months ago
  # 
  # bluetooth_low_energy: ^1.1.0
  # 5 months ago
  # 
  # bluetooth_advanced: ^0.0.83
  # 5 months ago
  # 
  # flutter_bluetooth_plus: ^0.1.16
  # 7 months ago
  # 
  # simpleblue: ^0.1.3
  # 7 months ago
  # 
  # flutter_blue_plugin: ^0.9.2
  # 9 months ago
  # 
  # flutter_scan_bluetooth: ^2.1.2
  # 11 months ago
  # 
  # quick_blue: ^0.4.1+1
  # 11 months ago
  # 
  # bluetooth_connector: ^0.0.3
  # 14 months ago
  # 
  # flutter_bluetooth_basic: ^0.1.7
  # 17 months ago
  # 
  # flutter_ble_lib: ^2.3.2
  # 2 years ago
  # 

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
